version: '2'
services:
  kongapay-international:
        build: .
        ports:
            - 7001:80
        volumes:
            - .:/src
        container_name: kongapay-international
        stdin_open: true
        tty: true
        env_file:
          - ./.env
